replace tini by start-stop

diff --git a/iou-base/Dockerfile b/iou-base/Dockerfile
--- a/iou-base/Dockerfile
+++ b/iou-base/Dockerfile
@@ -1,7 +1,7 @@
 FROM alpine
 
 #
-# install iouyap and (frozen) ioutools
+# install iouyap, (frozen) ioutools and start-stop
 #
 RUN set -ex \
     && dd if=/dev/zero bs=4 count=1 of=/etc/hostid \
@@ -19,13 +19,17 @@ RUN set -ex \
     && rm /usr/local/bin/ldd \
     && rm iou_export iou_import ldd \
     && cd - \
+    && mkdir -p /usr/local/sbin \
+    && url=`wget -q --no-check-certificate -O - https://api.github.com/repos/ehlers/start-stop/releases/latest | sed -n 's/^ *"browser_download_url": "\([^"]*_amd64\)".*/\1/p'` \
+    && if [ -z "$url" ]; then echo "start-stop not found" >&2; exit 1; fi \
+    && wget -q --no-check-certificate -O /usr/local/sbin/start-stop $url \
+    && chmod 755 /usr/local/sbin/start-stop \
     && apk del py2-cx_freeze wget \
     && rm -rf /var/cache/apk/*
 
 ADD libc-i386.tar.gz /
-ADD https://github.com/ehlers/start-stop/releases/download/v0.2/start-stop_0.2_amd64 /usr/local/bin/start-stop
 ADD do-start do-stop /etc/init.d/
 
-RUN chmod 755 /usr/local/bin/start-stop /etc/init.d/do-start /etc/init.d/do-stop
+RUN chmod 755 /etc/init.d/do-start /etc/init.d/do-stop
 
 CMD [ "start-stop", "/etc/init.d/do-start", "---", "/etc/init.d/do-stop" ]
