start-stop renamed to run-stop

diff --git a/iou-base/Dockerfile b/iou-base/Dockerfile
--- a/iou-base/Dockerfile
+++ b/iou-base/Dockerfile
@@ -1,7 +1,7 @@
 FROM alpine
 
 #
-# install iouyap, (frozen) ioutools and start-stop
+# install iouyap, (frozen) ioutools and run-stop
 #
 RUN set -ex \
     && dd if=/dev/zero bs=4 count=1 of=/etc/hostid \
@@ -20,16 +20,16 @@ RUN set -ex \
     && rm iou_export iou_import ldd \
     && cd - \
     && mkdir -p /usr/local/sbin \
-    && url=`wget -q -O - https://api.github.com/repos/ehlers/start-stop/releases/latest | sed -n 's/^ *"browser_download_url": "\([^"]*_amd64\)".*/\1/p'` \
-    && if [ -z "$url" ]; then echo "start-stop not found" >&2; exit 1; fi \
-    && wget -q -O /usr/local/sbin/start-stop $url \
-    && chmod 755 /usr/local/sbin/start-stop \
+    && url=`wget -q -O - https://api.github.com/repos/ehlers/run-stop/releases/latest | sed -n 's/^ *"browser_download_url": "\([^"]*_amd64\)".*/\1/p'` \
+    && if [ -z "$url" ]; then echo "run-stop not found" >&2; exit 1; fi \
+    && wget -q -O /usr/local/sbin/run-stop $url \
+    && chmod 755 /usr/local/sbin/run-stop \
     && apk del py2-cx_freeze wget ca-certificates \
     && rm -rf /var/cache/apk/*
 
 ADD libc-i386.tar.gz /
-ADD do-start do-stop /etc/init.d/
+ADD do-run do-stop /etc/init.d/
 
-RUN chmod 755 /etc/init.d/do-start /etc/init.d/do-stop
+RUN chmod 755 /etc/init.d/do-run /etc/init.d/do-stop
 
-CMD [ "start-stop", "/etc/init.d/do-start", "---", "/etc/init.d/do-stop" ]
+CMD [ "run-stop", "/etc/init.d/do-run", "---", "/etc/init.d/do-stop" ]
